function buildRecognitionSystem()
% Creates vision.mat. Generates training features for all of the training images.

	load('dictionary.mat');
	load('../data/traintest.mat');
%%     
    layerNum=3;
    [filterBank] = createFilterBank() ;
    dictionarySize=size(dictionary,2);
	% TODO create train_features
    N=length(train_imagenames);
    train_features=zeros(dictionarySize * (4^layerNum - 1)/3,N);
    
 %% get image features from train images
 
    for i=1:N
        
        restr=strrep(train_imagenames{i},'.jpg','.mat'); 
        % create a path to wordmaps generated by batchtovisualwords
        restr=['../data/' restr];
        load(restr);
        % load wordmap for each image in 
        train_features(:,i)=getImageFeaturesSPM(layerNum, wordMap, dictionarySize);
    end
 %%   
    save('vision.mat', 'filterBank', 'dictionary', 'train_features', 'train_labels');

end